title: Godeizx
description: HTB boxes, CTFs, and security research notes.
baseurl: "/Writeups"
url: "https://DiogoRoq.github.io"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

color_scheme: dark
search_enabled: true

aux_links:
  "View on GitHub":
    - "https://github.com/DiogoRoq/Writeups"
aux_links_new_tab: true

heading_anchors: true

nav_sort: case_insensitive

footer_content: "All content for authorized security testing / CTF / educational purposes."

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
